"""Scheduler

Revision ID: 3ac946cca6cd
Revises: 
Create Date: 2020-12-03 14:28:22.250535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac946cca6cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datesAvail', sa.DateTime(), nullable=True),
    sa.Column('datesBlocked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrLocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetAddress1', sa.String(length=100), nullable=True),
    sa.Column('streetAddress2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('userType', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=100), nullable=False),
    sa.Column('contactName', sa.String(length=100), nullable=False),
    sa.Column('contactPhone', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('userId_fk', sa.Integer(), nullable=False),
    sa.Column('calendarId_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendarId_fk'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['userId_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staffType', sa.String(length=40), nullable=False),
    sa.Column('assigned', sa.Boolean(), nullable=False),
    sa.Column('contrLocationId_fk', sa.Integer(), nullable=False),
    sa.Column('userid_fk', sa.Integer(), nullable=False),
    sa.Column('calendarId_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendarId_fk'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['contrLocationId_fk'], ['contrLocations.id'], ),
    sa.ForeignKeyConstraint(['userid_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coLocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyId_fk', sa.Integer(), nullable=True),
    sa.Column('streetAddress1', sa.String(length=100), nullable=True),
    sa.Column('streetAddress2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId_fk'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('contractorId_fk', sa.Integer(), nullable=False),
    sa.Column('companyId_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId_fk'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contractorId_fk'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placements')
    op.drop_table('coLocations')
    op.drop_table('contractors')
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_table('contrLocations')
    op.drop_table('calendars')
    # ### end Alembic commands ###
