"""Init

Revision ID: 738d65aac33c
Revises: 
Create Date: 2020-12-16 17:45:45.052915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738d65aac33c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('userType', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId_fk', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staffType', sa.String(length=40), nullable=False),
    sa.Column('userid_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid_fk')
    )
    op.create_table('blockedDates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractorId_fk', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractorId_fk'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companyContacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyId_fk', sa.Integer(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('addr1', sa.String(length=100), nullable=True),
    sa.Column('addr2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId_fk'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractorContacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractorId_fk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('addr1', sa.String(length=100), nullable=True),
    sa.Column('addr2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractorId_fk'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractorId_fk')
    )
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('contractorId_fk', sa.Integer(), nullable=False),
    sa.Column('companyId_fk', sa.Integer(), nullable=False),
    sa.Column('companyContactId_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyContactId_fk'], ['companyContacts.id'], ),
    sa.ForeignKeyConstraint(['companyId_fk'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contractorId_fk'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placements')
    op.drop_table('contractorContacts')
    op.drop_table('companyContacts')
    op.drop_table('blockedDates')
    op.drop_table('contractors')
    op.drop_table('companies')
    op.drop_table('users')
    # ### end Alembic commands ###
